---
title: "taskd"
author: "Sriram Boppana"
date: "November 19, 2017"
output: html_document
---


```{r install nhanesA}
#install.packages('nhanesA') #install nhanes
```

```{r Setup}
rm(list=ls()) #clear workspace

fn <- "raw_data_file.csv"
fn2 <- "filtered_data.csv"
if (file.exists(fn)) file.remove(fn) #remove raw_data file if it already exists (raw_data_file is the export from R to csv of nhanes dataset )
if (file.exists(fn2)) file.remove(fn2) #remove filtered_data file if it already exists (filtered_data is the export from R to csv of nhanes dataset )

library(ggplot2)
library(tibble)
library(readr)
library(dplyr)
library(NHANES)
library(nhanesA)
library(tidyverse)
```

Uploading the raw data and export it to CSV
```{r Raw data}
browseNHANES(2013, 'LAB', 'ALB_CR_H') # open Albumin & Creatinine - Urine (ALB_CR_H) weblink
browseNHANES(2013, 'LAB', 'GHB_H') # open glycemohemoglobin values
browseNHANES(2013, 'Q', 'DIQ_H') #open data for diabetes questionare
browseNHANES(2013, 'E', 'BMX_H') #body measurements
browseNHANES(2013, 'Q', 'PAQ_H') #physical activity
browseNHANES(2013, 'DEMO', 'DEMO_H') #demographics for age

alb <- nhanes('ALB_CR_H') %>%  #import data into raw_data_tible
  select("SEQN", "URXUMA") %>%
  filter(complete.cases("URXUMA")) #eliminate NA in outcome

glyc <- nhanes('GHB_H')  %>%
  select("SEQN", "LBXGH")
  
diab <- nhanes('DIQ_H') %>%  #import data into raw_data_tible
  select("SEQN", "DIQ010")

act <- (nhanes('PAQ_H')) %>% #days of 60mins of physical activity a day
  select("SEQN", "PAQ706")

age <- (nhanes('DEMO_H')) %>% 
  select("SEQN", "RIDAGEYR")

wait <- (nhanes('BMX_H')) %>% #BMI
  select("SEQN", "BMXBMI")

raw_data = left_join(alb, glyc, by = "SEQN") #combining everything together
raw_data = left_join(raw_data, diab, by = "SEQN")
raw_data = left_join(raw_data,act, by = "SEQN")
raw_data = left_join(raw_data, age, by = "SEQN")
raw_data = left_join(raw_data, wait, by = "SEQN")

```

test new csv file
```{r upload raw data again}
write.csv(raw_data, file = "raw_data_file.csv", row.names=FALSE) # export to csv file
raw_data2 <- read_csv("raw_data_file.csv") #read same csv again for proof that the original csv was exported properly
rename(ID = SEQN, raw_data2, albumin = URXUMA, a1c_hemoglobin = LBXGH, diagnoses = DIQ010, physical_activity= PAQ706, age = RIDAGEYR, BMI = BMXBMI)

```

```{r filter data}
write.csv(raw_data2, file = "filtered_data.csv", row.names=FALSE)
```

